---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/26 10:55
---
local mod = {}
local modName = "WebDKP"
_G[modName] = mod
local translations = {}
mod.translations = translations