---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/26 10:30
---

if (GetLocale() ~= "zhCN") then
    return
end

local L = WebDKP.translations

L.CLASS_WARLOCK = "术士"
L.CLASS_Warrior = "战士"
L.CLASS_Hunter = "猎人"
L.CLASS_Mage = "法师"
L.CLASS_Priest = "牧师"
L.CLASS_Druid = "德鲁伊"
L.CLASS_Paladin = "圣骑士"
L.CLASS_Shaman = "萨满祭司"
L.CLASS_Rogue = "潜行者"
L.CLASS_Death_Knight = "死亡骑士"