---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/26 10:30
---
local L = WebDKP.translations

--CLASS NAME
L.CLASS_WARLOCK = "Warlock"
L.CLASS_WARRIOR = "Warrior"
L.CLASS_HUNTER = "Hunter"
L.CLASS_MAGE = "Mage"
L.CLASS_PRIEST = "Priest"
L.CLASS_DRUID = "Druid"
L.CLASS_PALADIN = "Paladin"
L.CLASS_SHAMAN = "Shaman"
L.CLASS_ROGUE = "Rogue"
L.CLASS_DEATH_KNIGHT = "Death Knight"

L.CLASS_CASTERS = "Casters"
L.CLASS_MELEE = "Melee"
L.CLASS_HEALER = "Healer"
L.CLASS_CHAIN = "Chain"
L.CLASS_CLOTH = "Cloth"
L.CLASS_LEATHER = "Leather"
L.CLASS_PLATE = "Plate"