---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/26 10:30
---

if (GetLocale() ~= "zhCN") then
    return
end

local L = WebDKP.translations

L.CLASS_NAME = {
    ["Warlock"] = "术士",
    ["Warrior"] = "战士",
    ["Hunter"] = "猎人",
    ["Mage"] = "法师",
    ["Priest"] = "牧师",
    ["Druid"] = "德鲁伊",
    ["Paladin"] = "圣骑士",
    ["Shaman"] = "萨满祭司",
    ["Rogue"] = "潜行者",
}