---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/26 10:30
---
local L = WebDKP.translations

--CLASS NAME
L.CLASS_WARLOCK = "Warlock"
L.CLASS_Warrior = "Warrior"
L.CLASS_Hunter = "Hunter"
L.CLASS_Mage = "Mage"
L.CLASS_Priest = "Priest"
L.CLASS_Druid = "Druid"
L.CLASS_Paladin = "Paladin"
L.CLASS_Shaman = "Shaman"
L.CLASS_Rogue = "Rogue"
L.CLASS_Death_Knight = "Death Knight"

L.CLASS_Casters = "Casters"
L.CLASS_Melee = "Melee"
L.CLASS_Healer = "Healer"
L.CLASS_Chain = "Chain"
L.CLASS_Cloth = "Cloth"
L.CLASS_Leather = "Leather"
L.CLASS_Plate = "Plate"