---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/26 10:30
---

if (GetLocale() ~= "zhCN") then
    return
end

local L = WebDKP.translations

L.CLASS_WARLOCK = "术士"
L.CLASS_WARRIOR = "战士"
L.CLASS_HUNTER = "猎人"
L.CLASS_MAGE = "法师"
L.CLASS_PRIEST = "牧师"
L.CLASS_DRUID = "德鲁伊"
L.CLASS_PALADIN = "圣骑士"
L.CLASS_SHAMAN = "萨满祭司"
L.CLASS_ROGUE = "潜行者"
L.CLASS_DEATH_KNIGHT = "死亡骑士"