---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/26 10:30
---
local L = WebDKP.translations

L.TAB_FILTER="Filters"

--TAB FOR FILTER
L.FILTER_CLASS_WARLOCK = "Warlock"
L.FILTER_CLASS_WARRIOR = "Warrior"
L.FILTER_CLASS_HUNTER = "Hunter"
L.FILTER_CLASS_MAGE = "Mage"
L.FILTER_CLASS_PRIEST = "Priest"
L.FILTER_CLASS_DRUID = "Druid"
L.FILTER_CLASS_PALADIN = "Paladin"
L.FILTER_CLASS_SHAMAN = "Shaman"
L.FILTER_CLASS_ROGUE = "Rogue"
L.FILTER_CLASS_DEATH_KNIGHT = "Death Knight"

L.FILTER_CLASS_CASTERS = "Casters"
L.FILTER_CLASS_MELEE = "Melee"
L.FILTER_CLASS_HEALER = "Healer"
L.FILTER_CLASS_CHAIN = "Chain"
L.FILTER_CLASS_CLOTH = "Cloth"
L.FILTER_CLASS_LEATHER = "Leather"
L.FILTER_CLASS_PLATE = "Plate"

L.FILTER_CHECK_ALL = "Check All"
L.FILTER_UNCHECK_ALL = "Uncheck All"
L.FILTER_ONLY_SHOW_PLAYERS_IN_CURRENT_GROUP = "Only show players in current group"
L.FILTER_ONLY_SHOW_PLAYERS_IN_YOUR_GUILD="Only show players in your guild"
L.FILTER_ONLY_ONLINE_GUILD_MEMBERS= "Only Online Guild Members"
L.FILTER_EXCLUDE_ALL_ALTS="Exclude All Alts"
L.FILTER_EXCLUDE_ALTS_NOT_IN_PARTY= "Exclude Alts Not In Party"
L.FILTER_INCLUDE_STANDBY_PLAYERS="Include Standby Players"
L.FILTER_LIMIT_TO_STANDBY_PLAYERS="Limit to Standby Players"

--TAB FOR AWARD DKP